name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ develop, release ]


jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Load Next Cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/dist/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Prepare artifact
        run: |
          tar -czf fuelrats-com.tar.gz \
            .config \
            .yarn/plugins \
            .yarn/releases \
            dist \
            public \
            scripts \
            .nvmrc \
            CHANGELOG.md \
            LICENSE \
            .yarnrc.yml \
            next.config.js \
            package.json \
            README.md \
            yarn.lock

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: fuelrats-com
          path: fuelrats-com.tar.gz

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: publish

    env:
      NODE_ENV: production

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fuelrats-com

      - name: Extract artifact
        run: |
          tar -xzf fuelrats-com.tar.gz
          rm fuelrats-com.tar.gz

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.FR_SSH_KEY }}
          known_hosts: ${{ secrets.FR_KNOWN_HOSTS }}

      - name: Deploy
        run: sh ./scripts/deploy.sh
